### ISSUE TITLE
Renders incorrectly after tp

### ISSUE THREAD

**Issue by cheezychicken** [bermudalocket/Euclid#2]
When I leave modmode with the area still selected it does this:
![2019-07-30_20 48 42](https://user-images.githubusercontent.com/53493763/62160311-8b9f5d00-b30b-11e9-9ed7-4ad4735b645b.png)
Haven't tried just flying far away, so can't say if its the sudden coords change or just the distance from selection.

**Comment by bermudalocket** [comment]
Did you do your ModMode business in the same world as when you entered ModMode?

**Comment by cheezychicken** [comment]
Yup, same world throughout.

**Comment by bermudalocket** [comment]
Another question: did you make the selection in the same area that you returned to when you exited ModMode? Or was your selection made in a totally different area of the map?
