### ISSUE TITLE
//deselect does not hide wireframe

### ISSUE THREAD

**Issue by bermudalocket** [bermudalocket/Euclid#5]

**Comment by bermudalocket** [comment]
@KevFerguson I actually can't reproduce this bug. Can you provide more info, e.g. any commands you ran beforehand?

**Comment by KevFerguson** [comment]
Hello,
I can reproduce it and provide a screenshot too. I'm not near my gaming PC
until later in the week, sadly.

**Comment by KevFerguson** [comment]
I've attached a screenshot and the log from a recent Minecraft session (with stacktrace) that illustrate what I'm seeing. 

In this example, I've been using a similar pattern of operations to those I've listed below. Although the choice of block is irrelevant as it happens with any block.

1. Select region
2. Expand region by 2 blocks in 1 or more directions
3. Set expanded region to Smooth Sandstone
4. Deselect region with //deselect
5. Repeat step one 
       _or_ 
    Select new region which now has ghosting of previous expand operation (see screenshot)
6. Set region to Smooth Sandstone
7. Deselect region resulting in crash to Desktop

[issue5.txt](https://github.com/bermudalocket/Euclid/files/3538103/issue5.txt)
![issue5](https://user-images.githubusercontent.com/254956/63649727-2b001600-c739-11e9-95eb-59e6c56d1c39.jpg)

**Comment by bermudalocket** [comment]
@KevFerguson Thanks for following up! That's very interesting... I'm wondering if there's an issue with WorldEdit not relaying the deselection. Any chance you can do that same experiment one more time, but document exactly which commands you use? I'm having a little trouble following closely and want to make sure I have all the information.

**Comment by KevFerguson** [comment]
I found a simple, reliable way to recreate it!

I've disabled all mods other than Fabric API, Euclid, and WorldEdit to eliminate any conflicts there. I then created a simple area to test. I've found that I can get a CTD in three simple steps:

Select the area
![javaw_2019-08-25_22-04-33_1](https://user-images.githubusercontent.com/254956/63655858-2f522080-c785-11e9-87c9-4b586504985e.png)

Expand the area by 2 blocks north (you don't even need to press Enter, as long as the ghost blocks have been displayed)
![javaw_2019-08-25_22-05-09_2](https://user-images.githubusercontent.com/254956/63655860-311be400-c785-11e9-9eb9-ee5b120f006d.png)

type //deselect, hit enter, and CTD.
![javaw_2019-08-25_22-06-10_3](https://user-images.githubusercontent.com/254956/63655861-3416d480-c785-11e9-9cee-9cc8c171bcbc.png)

Minecraft log for the above: [issue5_1.txt](https://github.com/bermudalocket/Euclid/files/3538641/issue5_1.txt)

**Comment by bermudalocket** [comment]
@KevFerguson Perfect, thank you! I'll try my best to push out beta 4 sometime this week. I've been much busier than I expected.

**Comment by KevFerguson** [comment]
Glad to have been of help. Can't wait to try Beta 4, but do take your time.
Better that it's stable release and not rushed.
