### ISSUE TITLE
Add support for CoreProtect

### ISSUE THREAD

**Issue by paradox460** [bermudalocket/Euclid#6]
The LogBlock support you have is very nice, but it would be nice to see CoreProtect support as well

https://www.spigotmc.org/resources/coreprotect.8631/

Someone else mentioned this on the curse page, but they didn't open the ticket here, so I felt like I should

**Comment by bermudalocket** [comment]
Disregard issue closure.

**Comment by ryantheleach** [comment]
Thanks paradox for opening the issue, I was redirected here after asking about watson and modmode. Also interested in this.

**Comment by locke-d** [comment]
I also would like to request support for coreprotect. Thank you for your consideration. The plugin looks great so far.

**Comment by iCaitlyn** [comment]
Looking forward to seeing the inclusion of CoreProtect support as well! Thanks in advance!

**Comment by bermudalocket** [comment]
Progress can be tracked here: https://github.com/bermudalocket/Euclid/projects/2
