### ISSUE TITLE
Perspective

### ISSUE THREAD

**Issue by emperorcake** [bermudalocket/Euclid#7]
**Describe the bug**
Wireframe follows thirdperson movement and therefore goes out of selection range.

**To Reproduce**
1. Select region
2. Look at selection in firstperson
3. Look at selection in thirdperson (F5)

**Expected behavior**
That the wireframe would stay in the selection, and not follow thirdperson movement.

**Screenshots and/or Logs**
https://i.imgur.com/fHqyJJG.jpg
https://i.imgur.com/vF023Kp.jpg

**Environment**
Fabric version

**Comment by bermudalocket** [comment]
Third-person view support acknowledged! Perfect issue report; thanks for making my life easier.

**Comment by bermudalocket** [comment]
This was added in 1.0 beta 6.
