### ISSUE TITLE
Add some delay between login and /we cui posted in chat

### ISSUE THREAD

**Issue by DmitryRendov** [bermudalocket/Euclid#8]
**Is your feature request related to a problem? Please describe.**
subj

**Describe the solution you'd like**
some delay

**Additional context**
some servers kick players due to ./we cui command to fast...

**Comment by Wissotsky** [comment]
Because of this prevents me from playing on most servers

**Comment by HvPanda** [comment]
Same problem here. We love the idea but it auto kicks me from the server for to fast typing.

**Comment by amnotbananaama** [comment]
1.0.0-beta6 was uploaded to CurseForge on January 1st with this functionality. See https://www.curseforge.com/minecraft/mc-mods/euclid/files/2852734. This issue can be considered closed.
